version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - 4444:4444 # Selenium service
      - 5900:5900 # VNC server
      - 7900:7900 # VNC browser client

  node:
    image: node:20
    command: bash -c "npm i && ./wait-for-selenium.sh selenium:4444 && SELENIUM=selenium PLAYER=Bitmovin npm run test"
    volumes:
      - ./:/project
    working_dir: /project
    tty: true
    depends_on:
      - selenium
