version: '3'
services:
  chrome:
    image: selenium/standalone-chrome
    shm_size: '2gb'
    ports:
      - 4444:4444 # Selenium service
      - 5900:5900 # VNC server
      - 7900:7900 # VNC browser client
  node:
    image: node:20
    #command: bash -c "sleep 30 && npm i && BROWSER=chrome SELENIUM=chrome npm run test"
    volumes:
      - ./../../testing/:/project
    working_dir: /project
    tty: true
    depends_on:
      - chrome
  node-demo-app:
    image: node:20
    command: bash -c "npm i && npm run build && npm run dev"
    volumes:
      - ./../../packages/cmcd-validator-demo-app/:/code
    working_dir: /code
    tty: true
    ports:
      - 5173:5173

