name: Create Release
run-name: ${{ github.actor }} Run the Release Build 🚀
on:
  push:
    branches: [ 79-m1-config-github-action-to-create-release ]
  pull_request:
    branches: [ main ]
jobs:
  Build-with-npm:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build Start"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: git config user.name "${{ github.actor }}"
      - run: git config user.email "${{ github.actor}}@users.noreply.github.com"
      - run: git status
      - run: npm run pre-realese
      - name: Publish package to NPM 📦
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

