name: Run Jest Tests
run-name: ${{ github.actor }} Run Jest Tests
on:
  pull_request:
  push:
    branches:
      - 77-m1-config-github-action-to-run-test-and-linter
jobs:
  Run-the-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: "Run the tests"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm install
          npm run build